### ISSUE TITLE
MRecordRTC gif recording broken

### ISSUE THREAD

**Issue by thijstriemstra** [muaz-khan/RecordRTC#213]
Gif recording is broken in MRecordRTC; it will always throw this error:

```javascript
        if (!mediaType.audio && !mediaType.video) {
            throw 'MediaStream must have either audio or video tracks.';
        }
```

**Comment by muaz-khan** [comment]
Please test `{ gif:true }`:

```javascript
mRecordRTC.mediaType = {
   gif: true
};
```

**Comment by thijstriemstra** [comment]
thanks @muaz-khan, fixed now.

**Comment by thijstriemstra** [comment]
@muaz-khan can you publish the latest to npm?

**Comment by muaz-khan** [comment]
This `gif` solution is already published to NPM. Version 5.4.1.

**Comment by thijstriemstra** [comment]
ok thanks!

**Comment by bagwaa** [comment]
I'm still having this issue even in `5.4.1` is this a known bug or should I open a new issue?
