### ISSUE TITLE
After "stopRecording" camera still busy.

### ISSUE THREAD

**Issue by sctaix** [muaz-khan/RecordRTC#396]
[system info]
window10
nw.js v0.27.3
Node v9.3.0
Chromium 63.0.3239.108

Hi,

startRecording and stopRecording are working very well, but my webcam is still in working after stopRecording function called! *webcam LED does not turn off.

So, I tested that start & stop recording in my nw application and open RecordRTC demo page which is "https://www.webrtc-experiment.com/RecordRTC/", click the "Start Recording" button then console said "(index):391 onMediaCapturingFailed: {name: "NotReadableError", message: "", constraint: "", toString: ƒ}"

any idea?

**Comment by jaymo107** [comment]
I think the `AudioContext` needs to be stopped/cleared as it's still listening to the device, off the top of my head now I can't remember how it's done. But I'm pretty sure it's something to do with that, if that's what you mean?

**Comment by muaz-khan** [comment]
@sctaix please check this page:

```
chrome://settings/content/camera?search=camera
```

Make sure that `webrtc-experiment.com` isn't added in the **blocked list**.

**Comment by huhobocot** [comment]
I have a same problem with multiStreamRecorder, then i try to recreate multiStreamRecorder befor every record attempt and after some iterations i got error : Failed to construct 'AudioContext': The number of hardware contexts provided..
I search for AudioContext.close()  and find that it was fixed a month ago but last release at dec 2017. I think it`s a time to create a new release.

**Comment by shogan94** [comment]
Did you ever figure this out? When  I start a record and stop it the camera is still showing busy like its recording. How can I explicitly say to turn the camera back off?

**Comment by muaz-khan** [comment]
@shogan94 you can try this:

```javascript
recorder.stopRecording(function() {
    var blob = recorder.getBlob();
    // now manually stop the camera
    cameraStream.getTracks().forEach(function(track) {
        track.stop();
    });
});
```

**Comment by mfaizan1** [comment]
> ```js
> cameraStream
> ```

@muaz-khan what `cameraStream` refers here ? is it same stream we get from` navigator.getUserMedia`
